spring.application.name=multiModalDemo

spring.ai.openai.api-key=${YOUR_OWN_KEY}

spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.temperature=0.4

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB